language: python
python:
- '3.6'
install:
- pip install ansible molecule paramiko apache-libcloud
- ansible-galaxy install -r "$(pwd)/molecule/default/requirements.yml"
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - ANSIBLE_HOST_KEY_CHECKING=False
  - secure: XSlevbwVGAYJMZE7Cr0vNWCOvgFnyftoe9L0UfaFdpZvk+b551PTCbprFsNA3zYPvk/Thsv7hXShpbHb2GmZUeTU574RLYf0P43hZzQsR6s/6tZJ2/rHmn3Fw2kqjgUCq8nzSfmCiiXQbuAP5SObptP0zd0o1X5wU0Gxk+CYDoWnW/AzDOVddtKVMqT0b/Jaf4IfETJWeWxR+ngdf/+nlcsy62JmgUgNPyV32nIOn+m5AO8S4JkIMqV/b7PVzpmMs0Boa9I6yLOxd/TbOek0NEMh4HCyVesVVb3c3U/Zs0p8JFuQQpI8H2cOTe5YMaDc3uZT2r3syg36qFpT7raySocmA5KbxVFJLDY7PakY07QxQ2cmXxHpHGKUShaz46OVbfM7TFJl3bq5u/36mPDAStZTHJuluSEuWSeVljaXGyf0yzn6i6NUo4PMn5SlXk1IM6yEEhKw7KlLOSl4oraNs0dtsvqTdHgUyPUVFga8OHOUJUHAn8ZeHO0kJkxX26z2p6cVVq0fD65qdu4vJndY6BxeCbGWM5HHJadBAtkVKHuhA9sS+qsCW6qtQzrkDRWJxNccT5dueMAt6Mv/qF4N9SAm56hxpm5iJCwUxK6uXqkFhF/Q0Ia8I0VENG/5xZHHJTjgZl1kDY1LOyDBQCwRSuzQ0cHTbBWPed/+CrhE4kI=
  - secure: aBUQowb2SvCmSGW8TdfxF4hT8ww3WxxEQw5G9PO6fMwnEIWYJVaIS+zkSO81iG/u647AYmoFEEnRhUc4GFe0k0M1TMKtUK5BAZ7kzkJqW175Xka0ffI7fZ9Ck/TLXsDbTdSKJjh34EWqV1bDVF6hKzuMT3t64gZWKCheRcMWjq58748hg/2KOtILHSxSLjTDAVAYmWNXZUTWQ+bBnZ00en050rSRwn+davWVM/rm6xUA7ZFxc92ecVQZZKFz2USi4yS9qiZs1epChK/6ICQjb7euCRCqKfIIJB9B29/xFImn6haYcfTF0lgIRWXsK5UAZtJMS3jaw35c1H/jemoZpB8uJYhkuvJqZWYsrN3+1ZFtqEAV5qUZI+KaGNBq8A1G/qQzWgYP3FmI3J879j8ammH+rWchvfDOr5Nx74xNVDNAt09YhyJGhZpvAUorzhndAmyu4q1DrDt3VErVsfttkGh63U0dX85Xdx1txcCvkCOo5kox4cLxWqXxsoHWxioLpQF653SFfkCtKqaQDxZ9zoxnqSuv4fnA7GbAS1In1TqN/UKUhihI1CAcD6Q/pcuhBVZlMKMuZaYantveEMEhxusFJcZpigsiL43Iqiw7Zs5tTonq+rqN4oHhXI+jcb6Gcl8rMxYHo4dIhjcJE3qE676WfmaQORe+eO81ylhLOqo=
  - secure: QhKpBXxPRH11YGlhbEE3QNV5JSq5QSgS4hVbu3qDkpWVXET833hlT9cjSTsyxcyMeLag1gLm42IbigWVf5V0Yx58FAeyxOPac1iPAaVSZ5uUW8VhPLSmAv6UIxelkZv0atmTsBmPKQtIrL+K9tPV9/6vfqVjOYkuj6BZxp70icJwPzUcRFjsjA6jF5BiXzhA3To5BFWaDBOVtWaGte4lkPhYGVFW/7U2+aEwU6eePjATohnBBVXhMH0d+eKAxvRI4rTde0I+/iDKhgwiYmC18Vg8AX56hzvdzOe+Cd10iPwUhw7IruJowQlQtDy4SIi0JTdCpXJQDODLR41Xi4yR3NvBg3C4OZzxTJTn+/5CLf1yELLdwPX6ZksVnsb4FbAPK4hX0sCjM1zRAxSAQzAXU+L2BrMq9WgpctDetr6C8redNXB6PRCy0fA8y+SBzgEAISqPXwQLyCYL8o+/6Aq78xyfHIYsbSiXnxoSCQ6Fc/UWat4jrfzFPxIQVFK0Q6tPmpQ7TgzCMsik+gbD2kbUHfS5ozbljsBrDmkl6od9t71I8gGSRKZOLImk9e6tx5SXzLZHTwPQCtsA9V6Le8TSGfrO0IeHBsaraP8SU5hboxnvcAgwh21dImvLMWJg2FfGEjIspTWScelmyc4HYo0Y0snLtO030vVyTfBGgql51z4=
script:
- molecule create
- molecule converge
- molecule verify
before_install:
- openssl aes-256-cbc -K $encrypted_069219259cd2_key -iv $encrypted_069219259cd2_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /home/travis/.ssh/config
