language: python
python:
- '3.6'
install:
- pip install ansible molecule paramiko apache-libcloud
- ansible-galaxy install -r "$(pwd)/molecule/default/requirements.yml"
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - ANSIBLE_HOST_KEY_CHECKING=False
  - secure: B+AtmUlylm2VaJurPWjiVPdEV+FspAKwjDES0LlZZSrt+BFTjexq6e2HBl8In0iPMcv+N/qE+29/PxL4hONjp2uKbzpLpCfdRUdNzDO2M8XMkFQHd/w/HE1Hbz8PPXiN/nbFwx+eswulBjhXCOZVgQh6Qdn24/7NsM55NEPoyS2agy950enauoYW8zM4GYN4qjFarGQlQOOHk4Aj/sybY4TQxDfyYJPFI8rndkASixk1jXm0EmvqhlYhVpH3qjuCHclfMVu84nVjhvqMrhkrVHggYCUyU/KnTFpx9/54fYLE8omhO1mSvlKvm3z3SJSz5d91yr8OHzBlDPSYu40Y0Te45vOEwjNAj3yEkEb5dCFb/+UWAjl3KDctgXv5oxLXLe0qeUsJJDeaGGH+05TR7G93WT2AyGQIKfl03D8NkARtbRZDcfp3Aa3pUbdiC5WWgFkYk9qiAtNkrIZp1mAOyiLsz84dqYFfr3PDekXgS77fHiJ2Xna6cbbfgBGWrzyIBknoS6x09dnxGcqAQVAbIygDwpXf7Ykj6oz8ND4or/6zrVyNRv3CmgUCHZr7+fojy+cD6e/aGsxBHPtgtT5cUTFhLSC/O2unh9zdgwb1TqQt+CBaPKc+8O6tYp7kSZk03zPSim8Dx3cSYPohYQQNr9wXVUZD/Lk/4ID+efV3vro=
  - secure: kMKQ5kBHL9nGWmrhnMHuMzfP7GdjS1Axw9oiq/IF8jSzLBQ20r4WFb+Xw/gFD+dmQcKr0sH2DcBfC6kihLQJZT67uYA6bcgD9nr57j1eYb+QymVlZU9n7vmlB5Pzlxoo2JRWilRY4c3Ovc3ODSpl9pEAnKkkfU849fgtsNUAuBSQfb+nAuUuWHRLvtI8psMDp7fWjc0wY73fzIVy9rDj8qzgaRb07g8y7jScuU104rAmtqnintUT/+z0w5s1lMZCI1XI1yFT9YDNzAPJoiB/hpEsZ0gTOKVo3zpkZUp5H8qKiapk4rz+fV2vUVMPRM6ZtJQuEbOeDnILb79bnPJ6zzXjQu8WKDbV3joi3yhdKEE4t4gf+TKhPfNVGHdVsPJH8RpIY3lA9D5uAFxH1oo9p8bH/RjRwN/clHLI6OaLB/aw7gwbC+WYf7+UPbYO73PiqaObaNFSS3scGPtbYkI5DJlbHS6KWPAJ0uu8E+acxAWE3nr4fPuXhOETwKGKA+ixzWL7AibmFWPHVtStxAeVYt8bWPa+VLWPuQ/JjUMAyRSo4hMbwIGyMOGwde8lDcV1/BRp+PrEDO7jjCIcwW1o3wXsUiAPiDnWdS4u9CCiUvEIpzOnIDDf4OohdpiPwcFcckpn45j/O8mRrHw9Ba7IPuFuvQ5RpqlrDCzPQPKg8lk=
  - secure: F5Wf9WxzAKAVrfHKavpzY8d7eIihkLQFVfJdn5kJ0rpRnpFar6jO3IwoCCY6ra7n2N9y+4adZr8l5eZm8qywzZI+dMA9L+lSRANt1+KsS931DqOaNP9x0BBcgvdl3pkWOuBTeX9czxSudq4HKES9wEaln0D2kFh0XnCvwa0TZBOYGbqTRATYluHCEGIeLCLG81ZYOoxwewLnkHo6fJPtcny/p4n28SBLxTiBCO0DvelwHjuWHGEnDaOPTtfU9i6/KlrvCGGoFwDTA+2F0L286p9lsXphst46tgR+NMyV69UAZe6rc/Qrwz7fmRhN2MbATleLVZG5rhj5LSJ6LKBQpblfMW2B6KAD8Gu/wxu18xOxlFwvGPeOxdwLjR9LYcW5Yc5Wur22B8FF+B5cNlUlnHpjI1cgRSpW03gaOxnrZ2ErbRV2gxjDB2cyjLVtXJcb0oYWHct2xeF2+swGWq7JjJF9x2UyJx6faJHUNamSykLOsqlqRU2hkR7zBPsyn05X44/HX3K1gtL5xyL0EWA/TqI/IzYhbss7uMv14kYlzW230tZE8Ie+1mn//4EyjEt21i7CAwDzH1/hR2Ji9ujFmgSqZWWjYr0dHNXOkffcLxtVga6PFHOzIkHXjy7kIr64Go6hh/9Q72RiBsWcKPjaHWxkWEff6MrDK8whSHUfN4A=
script:
- molecule create
- molecule converge
- molecule verify
before_install:
- openssl aes-256-cbc -K $encrypted_069219259cd2_key -iv $encrypted_069219259cd2_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /home/travis/.ssh/config
