language: python
python:
- '3.6'
install:
- pip install ansible molecule paramiko apache-libcloud
- ansible-galaxy install -r "$(pwd)/molecule/default/requirements.yml"
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - ANSIBLE_HOST_KEY_CHECKING=False
  - secure: 2tZhzpUyW2Wj6xtruLFlfrRILddnPRaFyTJSqo5QN3tcrvcjUUbbcQcT+rTTPwZ4TF0Hhha5wN94rV/itm3lGw8m66oT5rukauPnH51QFFJ4OAAYBeAA66I5Hx6clKqBRjH3RGt1aIymgaMvjakf8i1XbTQ1BCHMpnwmvvgmI++AHleM90ZYM+WEIhAvjcM6NUcQVOrayE0NAtKJ6nzIIc6P03S82N+3oncll0ef+xZd2AzVWYlarNxRa7A4S8xIM9z8YmkUWO6NBlh74LmBu2giT5NUQNVKr0pIEpyUKSHLcDQRid2TQUmy4VDX4ERyy0QKmO9C6lyJF+cRxbbkEKONmhUh5BkpKk7IlkrXLRD/3MsIuh5ws/1v7V8SueYeFNIJKfElfp600wS4pDKVFtTfDqR8qfJAPzbiVLUSlsEotYDYLzr67CvNIch+F/WY3yE2FFW2TuCdM8dGptDXTJ5Rds2YuuWbn7elSsGIFZ7H0beLsLJ3QkJINJRmwMBKHFbtHfozLdwGc3yqp6f6ZdvnAs4jPnJWaZ/SElEN55XQVasozZ1zf3WnAq4ptx08wG9s50j0wjAKRTLeRw0fEizvQJcm55PuvZ8V0FMr++EciI9xStj3NkOSZFdlNHwF6GekM5nzbOQvhS7eJ+c93pK4TetEfXLlM4tPfJ3/x/M=
  - secure: yIDTRFpXDzwg1h4PP+92QwmMk5S24t0bRlykxWZzaxIoZGH1mraLleGN4Ajg8XuX8bUywfDtTpBeHrVtTPlCIaMruzHvpQDDuP/450x2U0zTNqo341oWNpfSrh7QiIZcUZazMcEeMkA5C7A+3Nh43wpUJjSPMq3ZDmEB02CxAfvd5kc/yiFr11uvG6tYtrr/Atsm7KiCq+birC3BykGHjFPq/MeEfABIfQiEk2N5XhcqWaXSrwkfNa1At5D70AEaC0u3xKQGn3+qYxEhCXXF0IL7E047gSFHSQLoeCDetl6Tx7MzypGMUr/xMN2uhrlX4eOUk6PJjmrWPnlyrYIyGcje+g9ofEC5Oj928W0SKj7AIwyXPFeirGzpBS0FWTLVwmGxOoDo0Iqlhbn7C+Ii2nMAJhBc/I7eWn4zKBeiEEp4v/b4n6mHr8S5H/ZHP3UKo4Nf6unEjZkQEnSzS1HrMIvPthBZTPYYcl/tfB1Z6R8xs782iR6ZH5jq4Wkmv8xWqMJemOFjUDxT/J8kTmcXXf3j9uVV7p2lhdjxmAY395WAh0GMD+oVT9rKAU66pvwB9SoJxqVt4cgEf3ko7/BEh9oj70JZFRcerKkqOWyT/CmQgL3j1c/9VtV2OwRchNAuDQIH70OPnF4KHByyDTCNkrj5Ii3WX+QJB/bbpo8J+po=
  - secure: ksuTUOuurFtAYBV1VbHhZ9ASEytfeyBbp0P5bDv21h8lDIxFMocT9GFgOPn3Mbf8pD5Zr47Ez4WwB5IzeNexC3EaXWy/xcmX+vN3DcWHeEe4jMqgj/GujeVOeclqqshLiyV05p/zk/TjJtBS5H2ScVrYsq/Ci4YVXZBRfjQPbmyTtDwMoZAtaJuZvtWxjSM6kqogFy3xHRQ0Rso9t6skwwKUlOaVLsJ0VZsfR0IGPoGDlgzwszgfYTWr2Uhz/rPJ+1IJdgvzKIwsLY2WFtYXwxgtZXH1lbe0+iDXLUik3SBjRQFSYCHNojU5ZGdEYVPMUwK2X7FC+ocKep3RJPHnWY9dfQQRVZU3XbaU4NRXu1JZ4IDhxYxAph0XXynS6vKv2cqshGtZ933C+sI6bWYtwWIvDpbCRDb359/Y/moD8YYg52/UWm6JTIIGlL1nYXd9i9h+2xvoQunwGqsutaCRnaqpF/0ZpGxO5la+M9PCX0a7pUslF16/7h/cG36U13LyGDjV5bQPYI91ec1ojyHrvD+gr1X8X/dFe4yO00jagxVID9u3/HA5PyWXp0p5DM6bVmVkki48GI04wpf0JJbiJ+zNM8fHT6aFLsVPxks+GHD8IPPkNWXN4dwxQ/NFcM+/1lQmCdGjgtZVUSEGNq9OxcKxNUhC2DV8MZc845Kyi0I=
script:
- molecule create
- molecule converge
- molecule verify
before_install:
- openssl aes-256-cbc -K $encrypted_069219259cd2_key -iv $encrypted_069219259cd2_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /home/travis/.ssh/config
