language: python
python:
- '3.6'
dist: xenial
install:
- pip install ansible molecule paramiko apache-libcloud
- ansible-galaxy install -r "$(pwd)/molecule/default/requirements.yml"
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - ANSIBLE_HOST_KEY_CHECKING=False
  - secure: CSXvriq+HpdCzf4G0j9k2sGlOq39r1D1ebCJolTODZ14SPOGNxS7K23mal5/mb/3tavs79wI6CzgY4+dZSClTv7DmQ+tGoaXUwmxbA8r0F0iaMEm7L0EujM3rbJtwm2mpuYlc0QRncOUvB6QIsw8WeCPWontSPAo5/4jYUHHWhiImYWn7IUQEh5cBTI4MlG7qw5XUFBAAr54H3PmBpkle+LU2yoW8dD+Y42QTdyb7XZ/EP/SSUW5pTlVknXyJ5mBDXIYyj9Ohg4Xm61TcFqhkPG3ndl1iRixQ7iEPstPdJEakM+3+M5l50+E0moEx0hoQAdCZAjHS2bjBhgG+NyXzwO32BDX4hFSBp6/U/xoV4lepISqltJ9rqqQFFuHwUOYZ8v5qeIc7tbqP7pY1c01ITraSot6r+KgUdWARrp3ZtxVFPXAW56ZSuyLW0Z+s4y09p0RXoXeMFQo+YSxRpFTzS/xVFpWGWfTaRdUPjjm/A5LUdlopqhj3D/jshjkLMm/+y5I25rotM8l+FwuSPar8qw+3v3X0rLKrNn7GXR8QiUuDpNnlEF3rpMZNK/Kf1Oxj4F7oi5IipHc3PkTZs2eYl+O5LDp820Hb5is3gVKsvhqqcvowUlhVZlWrO5MBU0ZLknMN4Dm5eUnkmzZOjlxSl1U9iPSdXTAeDcSy7P8XZQ=
  - secure: grlv3vNickegkqFSwf5jPd8qedMYRd6Eijbyp86u6jb5f8aFGE5OqJ0wW+1fweJ7O1jaI+TvheIiSLZvOakdAMi9gcEcN1aGzs0lpQCUyxWFQpux6lEfwNrggG4Z/vJOWEMO8OHRGzor1Wck06J6H+eTOwjxO8KduDEfgTtxdFXzP6iEbV86I1zbVvHu92jFpazP3MYPY1nfdsYqGqV5JC1lDeRyPsVd5VJi8/zgfADSsg1zA6ZkBWSuedxwHRtHH/0AV159D1PpoMoiZlOW/bwWTREporfmxmogvAH1diuQENBx21DjmHqyiia26w1i5etjUK78J786ueQ1W9+QNCtKKkQgqLJkKdDUa5KJhg49t4EyKZvtoJzF0J8aXsN543EqTLOdgiWUT22BuDPmvhFnolgX/uw16xq6NkJmIQj3qPHRE/Q5EUb6UUoLH3jRBdSfCfBGv7c850xBGDucnkyDs1d46iR8TuUjsKTObFaXcFFH5LmTD6cUzQsO3ISGmmMRQ2jVvYYLD7hME7tnljEK0t6Hify6LX+VZf4oWvxkIoTUnOXpSRSONmLiXlTcQ4GtCEBZTw0ekdHt9SBwfKlPNE3r+hnOxwXZdkEQmCWl/SGYQA3Ub34E9PERS5wXuOQZSdOgPF6Sg1wQa4UQ5hqlPJ1GeRC9VnkP5BraWBQ=
script:
- molecule create
- molecule converge
- molecule verify
before_install:
- openssl aes-256-cbc -K $encrypted_f15630b0e3dc_key -iv $encrypted_f15630b0e3dc_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /home/travis/.ssh/config
notifications:
  slack:
    secure: fJrtzrPQlYN2AyNcugqkWRt7w7vgjSU7dkCCx5QgY3nh2TeOwFWcaJMxsvrxavL5fGYj4krf6bkZN7n7GjRXtRV5n/ksvjaTzZ2xhh0L5TKwvgsjmn/iRpZTg4kCbDaSP3jwTYHMizgcbvNUvfPHnrZvV0my7fgb8z39nb+2jX8OzGw8VOvYMX02D5LwsDP2eWTLtBOSf+u53mtoJRcR8eaEJugf25gb6ZgoH0CAfoOEbEFuSq0GqXGiqME88m6T9l9euqF4SaopJQM7kregNn4/A3F38FBJpBBYDiWrGvUgkQNk1qh9iWq643LgHBC/jaRQkCcsxAaiRuVCwH4yBtQOFXnCAZQ5QFelVIUBZdJWPrFL96Kk6fZ3CakOzFLAYVBbtcwu2Nu78j6/Ym8MTnmpCUwpCNNEiFT7W1avXbr0mnvt9VF3VYSEOHW7ZwCmX40HiCKY564aVFBbMGdW4GbomRzhNQYIG4VgVXY2tG+SsVBTfyKRXz4pMHNXEbrDCF4NYInlyvXQ5smyRcc+xNqk0JNCUSIkVMrgXwFq0jvyXuDAvBum5LIzyTX5Af8fDu+FEXY7yRv5c4MEZwg7QZiFrb/qwKxsF6adDXf/JSiNkK4jKpSTz2H3/QcajgqO/RH9FkNxW79L6H3/B+OFCZv9EIf3GcFP/gEwt6AFVls=
